version: "3.9"

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
      target: db
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5  

  python_img:
    build:
      context: .
      dockerfile: Dockerfile
      target: etl

    depends_on:
      mysql:
        condition: service_healthy
    restart: 
      on-failure    
    volumes:
      - /path/to/local/data:/data

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
      - python_img
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

##